function [avgMSE, avgMAPE, percentage] = fitnessIndexCrom(delays)

% Solve an Autoregression Problem with External Input with a NARX Neural Network
% Script generated by NTSTOOL
% Created Sat Jul 05 18:26:55 CEST 2014
    
    % Load workspace
    load('tempWork.mat');

    inputSeries = tonndata(estimationMatrix,false,false);
    targetSeries = tonndata(estimationTargets,false,false);

    % Create a Nonlinear Autoregressive Network with External Input
    inputDelays = 1:delays(1);
    feedbackDelays = 1:delays(2);
    hiddenLayerSize = 10;
    net = narxnet(inputDelays,feedbackDelays,hiddenLayerSize);

    % Prepare the Data for Training and Simulation
    % The function PREPARETS prepares timeseries data for a particular network,
    % shifting time by the minimum amount to fill input states and layer states.
    % Using PREPARETS allows you to keep your original time series data unchanged, while
    % easily customizing it for networks with differing numbers of delays, with
    % open loop or closed loop feedback modes.
    [inputs,inputStates,layerStates,targets] = preparets(net,inputSeries,{},targetSeries);
    %net.trainParam.showWindow = 0;

    % Setup Division of Data for Training, Validation, Testing
    net.divideParam.trainRatio = 70/100;
    net.divideParam.valRatio = 15/100;
    net.divideParam.testRatio = 15/100;

    % Set average variables to zero
    avgMSE = 0;
    avgMAPE = 0;
    percentage = 0;
    
    for i = 1:10
        % Train the Network
        [net,tr] = train(net,inputs,targets,inputStates,layerStates);

        % Test the Network
        outputs = net(inputs,inputStates,layerStates);
        performance = perform(net,targets,outputs);
        
        % Cell to Matrix to perform computations
        targMatrix = cell2mat(targets);
        outMatrix = cell2mat(outputs);
        
        % Compute MAPE and percentage for each train
        tmpMAPE = 0;
        tmpPerc = 0;
        len = size(targMatrix,2);
        for j = 1:len
            tmpMAPE = tmpMAPE + abs((targMatrix(1,j) - outMatrix(1,j)) / targMatrix(1,j));
            if(sign(targMatrix(1,j)) == sign(outMatrix(1,j)))
                tmpPerc = tmpPerc + 1;
            end
        end
        tmpMAPE = (tmpMAPE / len) * 100;
        tmpPerc = (tmpPerc / len) * 100;
        
        avgMAPE = avgMAPE + tmpMAPE;
        avgMSE = avgMSE + performance;
        percentage = percentage + tmpPerc;
        
    end
    
    % Compute average MSE and MAPE
    avgMSE = avgMSE / 10;
    avgMAPE = avgMAPE / 10;
    percentage = percentage / 10;
    
    % Plots
    % Uncomment these lines to enable various plots.
    %figure, plotperform(tr)
    %figure, plottrainstate(tr)
    %figure, plotregression(targets,outputs)
    %figure, plotresponse(targets,outputs)
    %figure, ploterrcorr(errors)
    %figure, plotinerrcorr(inputs,errors)
    
    % Save net
    save('net.mat','net');
end